// Generated by https://quicktype.io

export interface OrganizacionModel {
  Id:        string;
  tipo?:     TipoOrganizacion;
  nombre:    string;
  direccion: Direccion;
  auditoria: Auditoria;
  banner:    string;
}

export interface Auditoria {
  createdAt:     number;
  updatedAt:     number;
  modificadoPor: string;
}

export interface Direccion {
  Id:             string;
  calle:          string;
  numeroExterior: string;
  colonia:        string;
  codigoPostal:   string;
  estado:         string;
  directorio:     Directorio[];
}

export interface Directorio {
  Id:                string;
  nombre:            string;
  telefono:          string;
  esPrincipal:       boolean;
  correoElectronico: string;
  alias:             string;
}

export enum TipoOrganizacion{
  OrganizacionGubernamental = 1,
	OrganizacionNoGubernamental,
	OrganizacionSocialConFinesDeLucro,
	OrganizacionSocialSinFinesDeLucro,
	OrganizacionPrivada,
}