// Generated by https://quicktype.io

export interface ProyectoModel {
  Id:                    string;
  nombre:                string;
  objetivo:              string;
  activo:                boolean;
  banner:                string;
  area:                  string;
  auditoria:             AuditoriaModel;
  actividad:             string;
  voluntariosRequeridos: number;
}

export interface AuditoriaModel {
  createdAt:     number;
  updatedAt:     number;
  modificadoPor: string;
}
